select  

AVG(TDM.AGE) as AVG_AGE

FROM TRANSACTION_PRODUCTS AS TP

INNER JOIN TRANSACTION_DETAILS AS TD
ON TP.TRANSACTION_ID = TD.TRANSACTION_ID

INNER JOIN TRANSACTION_DEMOG AS TDM
ON TD.BUYER_MM_ID = TDM.MM_ID

INNER JOIN PRODUCT_MAP AS PM
ON TP.PRODUCT_ID = PM.PID
AND PM.CATEGORY = 'Furniture'