SELECT
COUNT(*) AS CNT

FROM (
SELECT DISTINCT TDM.MM_ID
FROM

TRANSACTION_PRODUCTS AS TP
INNER JOIN TRANSACTION_DETAILS AS TD
ON TD.TRANSACTION_ID = TP.TRANSACTION_ID
AND TP.PRODUCT_ID = '6' /* Jewelry */


INNER JOIN TRANSACTION_DEMOG AS TDM
ON TD.BUYER_MM_ID = TDM.MM_ID


WHERE TDM.GENDER = 'F')